# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-deployment
  labels:
    app: todo-flask
spec:
  replicas: 2 # Deploy 2 instances of your app
  selector:
    matchLabels:
      app: todo-flask
  template:
    metadata:
      labels:
        app: todo-flask
    spec:
      containers:
      - name: todo-flask-app
        # IMPORTANT: Replace the image name with your ACR Login Server + image name
        image: todo-flask 
        ports:
        - containerPort: 5000 # Flask runs on port 5000